---
title: "TidyTuesday: Volcanic Eruptions"
output: html_notebook
---

Install packages

```{r}
library(tidyverse)
library(ggridges)
```


Download data

```{r}
# Get the Data

volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
eruptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')
tree_rings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/tree_rings.csv')
sulfur <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/sulfur.csv')

```

volcano.csv

```{r}
names(volcano)
```

```{r}
head(volcano)
```


```{r}
volcano_type <- volcano %>%
    select(volcano_number, primary_volcano_type, elevation)
```

Make ggplot

```{r}
ggplot(volcano_type, aes(x = elevation, y = primary_volcano_type)) + geom_density_ridges()
```

Rock type

```{r}
rock_type <- volcano %>%
    select(volcano_number, major_rock_1, elevation, region)
```



```{r}
ggplot(rock_type, aes(x = elevation, y = major_rock_1, fill = major_rock_1)) + geom_density_ridges()
```

facet by region

```{r}
ggplot(rock_type, aes(x = elevation, y = major_rock_1, fill = major_rock_1)) + 
    geom_density_ridges() +
    facet_wrap(~region)
```
































Population and rock type

```{r}
population <- volcano %>%
    select(volcano_number, major_rock_1, elevation, population_within_5_km)
```

```{r}
ggplot(population, aes(x=elevation, y=population_within_5_km, color=major_rock_1)) + geom_point()
```


